#!/usr/bin/env python3
"""Render the canonical L9 CI Summary comment + machine-readable JSON.

Consumes ci_context.json (CI_CONTEXT_PATH, default ci_context.json) produced by
pr-pipeline.yml and emits:
  - ci_summary.md   : the stable-marker governance comment (Kernel layout)
  - ci_summary.json : machine-readable CI state for the future agent review loop

Marker: <!-- l9-ci-audit-marker: v1 --> (canonical CI audit plane, per audit-policy.yml).
No third-party dependencies. ASCII status tokens only.
"""

from __future__ import annotations

import json
import os
import sys

MARKER = "<!-- l9-ci-audit-marker: v1 -->"
MAX_COMMENT_CHARS = 65336

ICON = {
    "success": "[PASS]",
    "skipped": "[SKIP]",
    "failure": "[FAIL]",
    "cancelled": "[STOP]",
    "missing": "[MISS]",
}


def _icon(result: str) -> str:
    return ICON.get(str(result).lower(), f"[{str(result).upper()}]")


def _load_context() -> dict:
    path = os.environ.get("CI_CONTEXT_PATH", "ci_context.json")
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError) as exc:
        print(f"[WARN] could not read {path}: {exc}", file=sys.stderr)
        return {}


def main() -> int:
    ctx = _load_context()
    results = ctx.get("results", {}) if isinstance(ctx.get("results"), dict) else {}
    secret_findings = int(ctx.get("secret_findings", 0) or 0)

    blocking = secret_findings > 0 or any(
        str(results.get(j, "")).lower() in {"failure", "timed_out", "action_required"}
        for j in ("secret_scan",)
    )
    result_field = "FAIL" if blocking else "PASS"
    merge_meaning = "blocked_by_real_governance" if blocking else "advisory_only"

    advisory_jobs = [
        j
        for j, r in results.items()
        if j != "secret_scan"
        and str(r).lower() in {"failure", "timed_out", "action_required", "missing"}
    ]
    skipped_jobs = [j for j, r in results.items() if str(r).lower() == "skipped"]

    labels = ctx.get("labels") or []
    surfaces = ctx.get("relevant_surfaces") or []

    lines = [
        MARKER,
        "## L9 CI Summary",
        "### Status",
        "| Field | Value |",
        "|---|---|",
        f"| Result | {result_field} |",
        f"| Merge Meaning | {merge_meaning} |",
        f"| PR Class | {ctx.get('pr_class', 'unknown')} |",
        f"| Blocking Count | {1 if blocking else 0} |",
        f"| Advisory Count | {len(advisory_jobs)} |",
        f"| Skipped Count | {len(skipped_jobs)} |",
        "### Classifier",
        "| Signal | Value |",
        "|---|---|",
        f"| Changed files | {ctx.get('changed_count', 0)} |",
        f"| Relevant surfaces | {', '.join(surfaces) if surfaces else 'none'} |",
        f"| Labels | {', '.join(labels) if labels else 'none'} |",
        f"| Diff unknown | {bool(ctx.get('diff_unknown', False))} |",
        "### Gate Results",
        "| Gate | Result |",
        "|---|---|",
    ]
    for job, result in results.items():
        lines.append(f"| {job} | {_icon(result)} {result} |")

    lines.append("### Blocking Findings")
    lines.append("| Severity | Detail |")
    lines.append("|---|---|")
    if secret_findings > 0:
        lines.append(f"| CRITICAL | {secret_findings} newly-introduced secret finding(s) |")
    elif blocking:
        lines.append("| HIGH | secret_scan job failed |")
    else:
        lines.append("| - | none |")

    lines.append("### Next Action")
    if blocking:
        lines.append("- Required: remove the newly-introduced secret(s), rotate the exposed credential, then push.")
    else:
        lines.append("- Required: none. Gate passes.")
    lines.append("- Optional: address advisory findings (inherited debt is non-blocking on this node).")

    lines.append("---")
    lines.append("<!-- l9-agent-review-marker: v1 (prepared, advisory-only, not enabled) -->")
    lines.append("Generated by L9 CI")

    body = "\n".join(lines)
    if len(body) > MAX_COMMENT_CHARS:
        body = body[: MAX_COMMENT_CHARS - 80] + "\n\n... truncated due to GitHub comment limit ...\nGenerated by L9 CI"

    with open("ci_summary.md", "w", encoding="utf-8") as fh:
        fh.write(body)

    summary_json = {
        "marker": MARKER,
        "result": result_field,
        "merge_meaning": merge_meaning,
        "pr_class": ctx.get("pr_class", "unknown"),
        "diff_unknown": bool(ctx.get("diff_unknown", False)),
        "changed_count": ctx.get("changed_count", 0),
        "labels": labels,
        "relevant_surfaces": surfaces,
        "results": results,
        "secret_findings": secret_findings,
        "blocking": blocking,
        "advisory_jobs": advisory_jobs,
        "skipped_jobs": skipped_jobs,
    }
    with open("ci_summary.json", "w", encoding="utf-8") as fh:
        json.dump(summary_json, fh, indent=2, sort_keys=True)

    print(f"[INFO] rendered ci_summary.md ({len(body)} chars) + ci_summary.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
