"""Append or update the HARD INVARIANTS section of an AGENTS.md file from generated_invariants.yaml."""
from __future__ import annotations

from pathlib import Path

import typer
import yaml

app = typer.Typer()

MARKER_START = "<!-- L9-INVARIANTS-START -->"
MARKER_END = "<!-- L9-INVARIANTS-END -->"


def _render_block(invariants: list[dict]) -> str:
    lines = [MARKER_START, "", "## Hard Invariants (auto-generated by l9-ci-debt-intelligence)", ""]
    for inv in invariants:
        lines.append(f"- **{inv['id']}** — {inv['description']}")
        lines.append(f"  - Gate: {inv['gate']} | Severity: {inv['severity']} | Seen {inv['occurrences']}× in corpus")
        lines.append("")
    lines.append(MARKER_END)
    return "\n".join(lines)


@app.command()
def update(
    agents_md: Path = typer.Argument(..., help="Path to target AGENTS.md"),
    invariants_yaml: Path = typer.Option(Path("outputs/offense/generated_invariants.yaml")),
    dry_run: bool = typer.Option(False),
) -> None:
    data = yaml.safe_load(invariants_yaml.read_text())
    invariants = data.get("invariants", [])
    block = _render_block(invariants)

    if agents_md.exists():
        content = agents_md.read_text()
        if MARKER_START in content and MARKER_END in content:
            start = content.index(MARKER_START)
            end = content.index(MARKER_END) + len(MARKER_END)
            new_content = content[:start] + block + content[end:]
        else:
            new_content = content.rstrip() + "\n\n" + block + "\n"
    else:
        new_content = block + "\n"

    if dry_run:
        typer.echo(new_content)
    else:
        agents_md.write_text(new_content)
        typer.echo(f"Updated {agents_md} with {len(invariants)} invariants")


if __name__ == "__main__":
    app()
