"""Build a few-shot example block from high-quality resolved findings for use in agent prompts."""
from __future__ import annotations

import json
from pathlib import Path

import typer

app = typer.Typer()


@app.command()
def build(
    corpus_jsonl: Path = typer.Argument(Path("outputs/corpus/unified_findings.jsonl")),
    output_path: Path = typer.Option(Path("outputs/offense/CONTEXT_PRIMERS.md")),
    max_examples: int = typer.Option(20, help="Max examples per finding_id prefix"),
) -> None:
    """Select patched+green examples from corpus and render as Markdown few-shot primers."""
    examples: dict[str, list[dict]] = {}

    for raw in corpus_jsonl.read_text().splitlines():
        raw = raw.strip()
        if not raw:
            continue
        r = json.loads(raw)
        if r.get("action") != "patch" or r.get("classification") != "valid_current":
            continue
        fid = r.get("finding_id", "UNKNOWN")
        prefix = "-".join(fid.split("-")[:2])
        examples.setdefault(prefix, []).append(r)

    lines = ["# Context Primers — Few-Shot Examples\n",
             "_Auto-generated by `few_shot_loader.py`. Do not edit manually._\n"]

    for prefix, recs in sorted(examples.items()):
        lines.append(f"## {prefix}\n")
        for r in recs[:max_examples]:
            lines.append(f"### PR #{r.get('pr')} cycle {r.get('cycle')} — {r.get('finding_id')}\n")
            lines.append(f"**Location:** `{r.get('location', 'unknown')}`  ")
            lines.append(f"**Description:** {r.get('description', '')}  ")
            lines.append(f"**Action taken:** {r.get('action', '')}\n")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    typer.echo(f"Context primers ({sum(len(v) for v in examples.values())} examples) → {output_path}")


if __name__ == "__main__":
    app()
