"""Generate ast-grep YAML rules from corpus invariants."""
from __future__ import annotations

import re
from pathlib import Path

import typer
import yaml

app = typer.Typer()

# Template rules keyed by finding_id prefix
_RULE_TEMPLATES: dict[str, dict] = {
    "CI-IMPORT-001": {
        "id": "ci-import-001",
        "language": "yaml",
        "rule": {"pattern": "jobs:\n  $JOB:\n    steps:\n      - $STEP"},
        "message": "GHA job missing PYTHONPATH env var (CI-IMPORT-001). Add env: PYTHONPATH: ${{ github.workspace }} to the job.",
        "severity": "error",
        "note": "Auto-generated by l9-ci-debt-intelligence/corpus_to_astgrep.py",
    },
    "CI-DEPS-001": {
        "id": "ci-deps-001",
        "language": "toml",
        "rule": {"not": {"has": {"pattern": 'dependencies = [$$$]'}}},
        "message": "pyproject.toml missing [project.dependencies] (CI-DEPS-001). Add pydantic>=2.0 and other runtime deps.",
        "severity": "warning",
        "note": "Auto-generated by l9-ci-debt-intelligence/corpus_to_astgrep.py",
    },
    "API-DRIFT-001": {
        "id": "api-drift-001",
        "language": "python",
        "rule": {"pattern": "class ReviewReport"},
        "constraints": {"has": {"not": {"pattern": "suggested_tests"}}},
        "message": "ReviewReport missing suggested_tests field (API-DRIFT-001). Extend with SuggestedTest dataclass.",
        "severity": "error",
        "note": "Auto-generated by l9-ci-debt-intelligence/corpus_to_astgrep.py",
    },
}


@app.command()
def generate(
    invariants_yaml: Path = typer.Option(Path("outputs/offense/generated_invariants.yaml")),
    output_dir: Path = typer.Option(Path("outputs/defense/astgrep/rules")),
    sgconfig_path: Path = typer.Option(Path("outputs/defense/astgrep/sgconfig.yml")),
) -> None:
    import yaml as _yaml

    data = _yaml.safe_load(invariants_yaml.read_text()) if invariants_yaml.exists() else {"invariants": []}
    output_dir.mkdir(parents=True, exist_ok=True)
    rule_files: list[str] = []

    for fid, template in _RULE_TEMPLATES.items():
        rule_path = output_dir / f"{template['id']}.yaml"
        rule_path.write_text(_yaml.dump(template, sort_keys=False, allow_unicode=True))
        rule_files.append(str(rule_path.relative_to(sgconfig_path.parent)))
        typer.echo(f"  wrote {rule_path}")

    sgconfig = {
        "ruleDirs": ["rules"],
        "testConfigs": [{"testDir": "tests"}],
    }
    sgconfig_path.parent.mkdir(parents=True, exist_ok=True)
    sgconfig_path.write_text(_yaml.dump(sgconfig, sort_keys=False))
    typer.echo(f"ast-grep config → {sgconfig_path} ({len(rule_files)} rules)")


if __name__ == "__main__":
    app()
