#!/usr/bin/env python3
"""Generate project scaffolds for each active adapter topology."""
from __future__ import annotations
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed", file=sys.stderr)
    sys.exit(1)


GHA_CI_TEMPLATE = """\
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{{{ github.workspace }}}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install pydantic>=2.0 pyyaml jsonschema pytest ruff
      - name: Lint
        run: ruff check .
      - name: Test
        run: pytest -q
"""

PYPROJECT_TEMPLATE = """\
[project]
name = "your-project"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.0",
    "pyyaml",
    "jsonschema",
]

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
"""

PRECOMMIT_TEMPLATE = """\
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
"""

AGENTS_MD_TEMPLATE = """\
# AGENTS.md
# Auto-generated scaffold — l9-ci-debt-intelligence
# Inject current invariants before use.

## KNOWN ROOT CAUSES

{invariant_block}

## CI CONTRACT

- All GHA jobs that import Python modules MUST set PYTHONPATH.
- pydantic>=2.0 MUST be in [project.dependencies].
- Every GHA job calling Python scripts MUST have an Install deps step.
- tools/review/report.py MUST define SuggestedTest, load_json_report().
"""


def load_invariants() -> str:
    inv_path = Path("outputs/offense/generated_invariants.yaml")
    if not inv_path.exists():
        return "(no invariants generated yet — run corpus_to_invariants.py)"
    data = yaml.safe_load(inv_path.read_text(encoding="utf-8"))
    lines = []
    for inv in data.get("invariants", []):
        if inv.get("confidence") in {"high", "medium"}:
            lines.append(f"- [{inv['rule_id']}] {inv['invariant_statement']}")
    return "\n".join(lines) if lines else "(no high-confidence invariants)"


def write_scaffold(name: str, scaffolds_dir: Path, invariant_block: str) -> None:
    d = scaffolds_dir / name
    d.mkdir(parents=True, exist_ok=True)
    (d / ".github" / "workflows").mkdir(parents=True, exist_ok=True)
    (d / ".github" / "workflows" / "ci.yml").write_text(GHA_CI_TEMPLATE, encoding="utf-8")
    (d / "pyproject.toml").write_text(PYPROJECT_TEMPLATE, encoding="utf-8")
    (d / ".pre-commit-config.yaml").write_text(PRECOMMIT_TEMPLATE, encoding="utf-8")
    (d / "AGENTS.md").write_text(AGENTS_MD_TEMPLATE.format(invariant_block=invariant_block), encoding="utf-8")
    (d / "README.md").write_text(f"# {name} scaffold\nGenerated by l9-ci-debt-intelligence.\n", encoding="utf-8")


def main() -> int:
    scaffolds_dir = Path("outputs/defense/scaffolds")
    invariant_block = load_invariants()

    for topology in ["python-gha", "node-gha", "polyglot-gha"]:
        write_scaffold(topology, scaffolds_dir, invariant_block)
        print(f"OK: scaffold written for {topology}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
